language: python
matrix:
    include:
      # We put 3.6 first since this is where flake8 and docs are tested
      - python: 3.6
      - python: 2.7
      - python: 3.4
      - python: 3.5
      - python: 3.7

install:
  - travis_retry pip install --upgrade pip
  - travis_retry pip install --upgrade tox tox-travis

script:
  - tox -e test PRINT=1
  - tox
